"""③ 連絡先DB（CNT-xxx、新規独立）。

既存4DBと異なり、Notion側は現時点でtitleプロパティ「名前」のみを持つ空DB
（database_id=3b4d8ea8-d4f3-808d-9853-d9cdd3de39ae）として存在する。
titleは仕様書03節が想定していた「連絡先ID（自動採番）」ではなく、既存のNotion側
「名前」をそのまま使う（Notion側で既にtitleとして存在するため、名前を変更すると
Notion API側で不整合が起きる可能性がある）。氏名は「名前」titleが担うため、
仕様書03節の「氏名」テキストプロパティは重複となり新設しない。

その他のプロパティは仕様書03節の定義をベースに、既存4DBの命名慣習（relationの
参照先プロパティ名は「取引先マスター」等）に合わせて設計する。
"""

from __future__ import annotations

from src.db_schema.base import (
    DatabaseSchema,
    PropertyDefinition,
    PropertyType,
    RequirementLevel,
    SyncScope,
    common_internal_properties,
)

CONTACT_SCHEMA = DatabaseSchema(
    key="contact",
    display_name="連絡先DB",
    id_prefix="CNT-",
    kintone_key="担当者名1〜3（分割）",
    zoho_key="連絡先（リード）",
    zoho_api_module="Contacts",
    spreadsheet_sheet_name="連絡先",
    notion_database_id="3b4d8ea8-d4f3-808d-9853-d9cdd3de39ae",
    properties=(
        PropertyDefinition(
            name="名前",
            property_type=PropertyType.TITLE,
            requirement=RequirementLevel.REQUIRED,
            sync_scope=SyncScope.ALL_TOOLS,
            description="Notion側で既存のtitleプロパティ。氏名そのものを保持する",
        ),
        PropertyDefinition(
            name="取引先マスター",
            property_type=PropertyType.RELATION,
            requirement=RequirementLevel.REQUIRED,
            sync_scope=SyncScope.ALL_TOOLS,
            description="所属企業",
            relation_target="client_master",
        ),
        PropertyDefinition(
            name="部署",
            property_type=PropertyType.TEXT,
            requirement=RequirementLevel.OPTIONAL,
            sync_scope=SyncScope.ALL_TOOLS,
            description="Eightからの更新対象",
        ),
        PropertyDefinition(
            name="役職",
            property_type=PropertyType.TEXT,
            requirement=RequirementLevel.OPTIONAL,
            sync_scope=SyncScope.ALL_TOOLS,
            description="Eightからの更新対象",
        ),
        PropertyDefinition(
            name="メールアドレス",
            property_type=PropertyType.EMAIL,
            requirement=RequirementLevel.OPTIONAL,
            sync_scope=SyncScope.ALL_TOOLS,
            description="名寄せの一意キーとして使用",
        ),
        PropertyDefinition(
            name="携帯番号",
            property_type=PropertyType.PHONE,
            requirement=RequirementLevel.OPTIONAL,
            sync_scope=SyncScope.ALL_TOOLS,
        ),
        PropertyDefinition(
            name="直通TEL",
            property_type=PropertyType.PHONE,
            requirement=RequirementLevel.OPTIONAL,
            sync_scope=SyncScope.ALL_TOOLS,
        ),
        PropertyDefinition(
            name="Eight連携ID",
            property_type=PropertyType.TEXT,
            requirement=RequirementLevel.AUTO,
            sync_scope=SyncScope.NOTION_ONLY,
            description="Eight連携で自動投入",
        ),
        PropertyDefinition(
            name="名刺交換日",
            property_type=PropertyType.DATE,
            requirement=RequirementLevel.AUTO,
            sync_scope=SyncScope.NOTION_ONLY,
            description="Eight連携で自動投入",
        ),
        PropertyDefinition(
            name="名刺交換者",
            property_type=PropertyType.TEXT,
            requirement=RequirementLevel.AUTO,
            sync_scope=SyncScope.NOTION_ONLY,
            description="Eight連携で自動投入",
        ),
        PropertyDefinition(
            name="人事異動フラグ",
            property_type=PropertyType.CHECKBOX,
            requirement=RequirementLevel.AUTO,
            sync_scope=SyncScope.NOTION_ONLY,
            description="Eightで部署・役職の変更を検知した際にON",
        ),
        *common_internal_properties(),
    ),
)
